### ISSUE TITLE
Newest releases not available on PyPI

### ISSUE THREAD

**Issue by justbbetter** [zendesk/sunshine-conversations-python#8]
The documentation says to install with `pip install smooch`.  However, the latest version on PyPI is 3.12.0.  I developed against the latest online documentation  (https://docs.smooch.io/rest/), which is v1.1 of the API.  However, that requires v4.0.0 of this library or greater, which is not available on PyPI.  Please upload the latest releases to PyPI.

**Comment by DataWearsAHood** [comment]
Current latest version on PyPi is `smooch 5.34.0`
